package com.faberlic.billing.objects;
// Generated 15.04.2017 16:33:29 by Hibernate Tools 4.3.1



/**
 * BillingType generated by hbm2java
 */
public class BillingType  implements java.io.Serializable {


     private Integer id;
     private String name;

    public BillingType() {
    }

    public BillingType(String name) {
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


