package com.faberlic.billing.objects;
// Generated 15.04.2017 16:33:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Detailes generated by hbm2java
 */
public class Detailes  implements java.io.Serializable {


     private Long id;
     private Operators operators;
     private Phones phones;
     private Date calledAt;
     private String duration;
     private String recipient;
     private String zoneVtk;
     private String zonePs;
     private String service;
     private Float price;
     private Date period;

    public Detailes() {
    }

    public Detailes(Operators operators, Phones phones, Date calledAt, String duration, String recipient, String zoneVtk, String zonePs, String service, Float price, Date period) {
       this.operators = operators;
       this.phones = phones;
       this.calledAt = calledAt;
       this.duration = duration;
       this.recipient = recipient;
       this.zoneVtk = zoneVtk;
       this.zonePs = zonePs;
       this.service = service;
       this.price = price;
       this.period = period;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Operators getOperators() {
        return this.operators;
    }
    
    public void setOperators(Operators operators) {
        this.operators = operators;
    }
    public Phones getPhones() {
        return this.phones;
    }
    
    public void setPhones(Phones phones) {
        this.phones = phones;
    }
    public Date getCalledAt() {
        return this.calledAt;
    }
    
    public void setCalledAt(Date calledAt) {
        this.calledAt = calledAt;
    }
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }
    public String getRecipient() {
        return this.recipient;
    }
    
    public void setRecipient(String recipient) {
        this.recipient = recipient;
    }
    public String getZoneVtk() {
        return this.zoneVtk;
    }
    
    public void setZoneVtk(String zoneVtk) {
        this.zoneVtk = zoneVtk;
    }
    public String getZonePs() {
        return this.zonePs;
    }
    
    public void setZonePs(String zonePs) {
        this.zonePs = zonePs;
    }
    public String getService() {
        return this.service;
    }
    
    public void setService(String service) {
        this.service = service;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }
    public Date getPeriod() {
        return this.period;
    }
    
    public void setPeriod(Date period) {
        this.period = period;
    }




}


