package com.faberlic.billing.objects;
// Generated 15.04.2017 16:33:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private Integer id;
     private Accesses accesses;
     private Departments departments;
     private Employees employees;
     private Roles roles;
     private Trips trips;
     private String ldapGuid;
     private String fio;
     private String email;
     private Boolean ldapSync;
     private Set<Employees> employeeses = new HashSet<Employees>(0);
     private Set<Phones> phoneses = new HashSet<Phones>(0);

    public Employees() {
    }

	
    public Employees(Trips trips) {
        this.trips = trips;
    }
    public Employees(Accesses accesses, Departments departments, Employees employees, Roles roles, Trips trips, String ldapGuid, String fio, String email, Boolean ldapSync, Set<Employees> employeeses, Set<Phones> phoneses) {
       this.accesses = accesses;
       this.departments = departments;
       this.employees = employees;
       this.roles = roles;
       this.trips = trips;
       this.ldapGuid = ldapGuid;
       this.fio = fio;
       this.email = email;
       this.ldapSync = ldapSync;
       this.employeeses = employeeses;
       this.phoneses = phoneses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Accesses getAccesses() {
        return this.accesses;
    }
    
    public void setAccesses(Accesses accesses) {
        this.accesses = accesses;
    }
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public Trips getTrips() {
        return this.trips;
    }
    
    public void setTrips(Trips trips) {
        this.trips = trips;
    }
    public String getLdapGuid() {
        return this.ldapGuid;
    }
    
    public void setLdapGuid(String ldapGuid) {
        this.ldapGuid = ldapGuid;
    }
    public String getFio() {
        return this.fio;
    }
    
    public void setFio(String fio) {
        this.fio = fio;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getLdapSync() {
        return this.ldapSync;
    }
    
    public void setLdapSync(Boolean ldapSync) {
        this.ldapSync = ldapSync;
    }
    public Set<Employees> getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set<Employees> employeeses) {
        this.employeeses = employeeses;
    }
    public Set<Phones> getPhoneses() {
        return this.phoneses;
    }
    
    public void setPhoneses(Set<Phones> phoneses) {
        this.phoneses = phoneses;
    }




}


