package com.faberlic.billing.objects;
// Generated 15.04.2017 16:33:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Phones generated by hbm2java
 */
public class Phones  implements java.io.Serializable {


     private Integer id;
     private Employees employees;
     private String phone;
     private Integer limit;
     private String description;
     private Set<Detailes> detaileses = new HashSet<Detailes>(0);

    public Phones() {
    }

    public Phones(Employees employees, String phone, Integer limit, String description, Set<Detailes> detaileses) {
       this.employees = employees;
       this.phone = phone;
       this.limit = limit;
       this.description = description;
       this.detaileses = detaileses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Integer getLimit() {
        return this.limit;
    }
    
    public void setLimit(Integer limit) {
        this.limit = limit;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Detailes> getDetaileses() {
        return this.detaileses;
    }
    
    public void setDetaileses(Set<Detailes> detaileses) {
        this.detaileses = detaileses;
    }




}


