package com.faberlic.billing.objects;
// Generated 15.04.2017 16:33:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Trips generated by hbm2java
 */
public class Trips  implements java.io.Serializable {


     private int id;
     private Integer employeeId;
     private Date dateStart;
     private Date dateEnd;
     private String destinationPlace;
     private String document;
     private String target;
     private Employees employees;

    public Trips() {
    }

	
    public Trips(int id) {
        this.id = id;
    }
    public Trips(int id, Integer employeeId, Date dateStart, Date dateEnd, String destinationPlace, String document, String target, Employees employees) {
       this.id = id;
       this.employeeId = employeeId;
       this.dateStart = dateStart;
       this.dateEnd = dateEnd;
       this.destinationPlace = destinationPlace;
       this.document = document;
       this.target = target;
       this.employees = employees;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }
    public Date getDateEnd() {
        return this.dateEnd;
    }
    
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }
    public String getDestinationPlace() {
        return this.destinationPlace;
    }
    
    public void setDestinationPlace(String destinationPlace) {
        this.destinationPlace = destinationPlace;
    }
    public String getDocument() {
        return this.document;
    }
    
    public void setDocument(String document) {
        this.document = document;
    }
    public String getTarget() {
        return this.target;
    }
    
    public void setTarget(String target) {
        this.target = target;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }




}


