package com.faberlic.billing.objects;
// Generated 15.04.2017 16:33:29 by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String ldapSid;
     private String username;
     private String password;
     private byte isAdmin;

    public Users() {
    }

    public Users(String ldapSid, String username, String password, byte isAdmin) {
       this.ldapSid = ldapSid;
       this.username = username;
       this.password = password;
       this.isAdmin = isAdmin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLdapSid() {
        return this.ldapSid;
    }
    
    public void setLdapSid(String ldapSid) {
        this.ldapSid = ldapSid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public byte getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(byte isAdmin) {
        this.isAdmin = isAdmin;
    }




}


